drop table notification;

create table notification
(
	ID_NOTIF NUMBER(10),
	ID_ENSEIGNANT NUMBER(10)  NOT NULL,
	MESSAGE CHAR(500),
	CONSTRAINT PK_ID_NOTIF PRIMARY KEY(ID_NOTIF)
);

ALTER TABLE NOTIFICATION ADD (CONSTRAINT FK_ID_ENS
         FOREIGN KEY (ID_ENSEIGNANT)
              REFERENCES ENSEIGNANT (ID_ENSEIGNANT))   ;